language: node_js
node_js: 10
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: kIQ6NmrMoy6/jtkDiYlikBxW7eXs1Cl2bnKTWDWcj+82Pox+oWBMiqjFdQQPdlga2FcKtSzAKOomgb7rD65oT3qAf9TroyXjkxLgXhu5ISReTT6NIHRiDWfhO2rRM8OPpT991ULRWCzXB+SekvL3kT4uvkJ9s7eX5Ib6sgBRvyJoy84YueGB4OhEIg1GaA5c16JZzgDSo+XKoyNdQWkRL07MSWaFHAajBFx2ZOF1VB33dvy12z5CCfTuclUfxH/UjzP7oge5JvqtZfEY2Vy1Jbvrw4vhPypchNpyXCvLjQhN6KIfitiUiBoGJGUM7I4NzzWWOZVsVr5aVQwvHvMOflrQ1KAISjYRfWsTEaV2K/iVi68/1HJSEvRlpOFYMeur8G8BCzG1vrWkCY8K17Bt8MuY8sKTl9aBfWFbrG32VvB3qSGVrSTOznoB76utaMgdWo0rnreykFKeuxuT7mAEyEtlwgXbWVaKHOxAT3mMHmq/WeIL+uf/hmPA82CgrZT7KmIWfuaEL6S4uDhejdAo2jPfY03LZ+5YnVoTmGQVC2k8CrCTtNNZl/4z3Gvft3fsaJsazTFZEvtY407243APuX81davhXYrmuf9j9U3z7DvvOMi4PQoS9EycCLfT6ixOBpbUwug23Fm92HvyCEomghWdisyPwiHpGUtqZb8XGYU=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-local
    branch: master
