language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: zwU24eb+37sHUmSWmtGNXFNv50+tDNmLesD2zNGFjA4pGjaCjtrvtAFe2eCImOXt7+8szDORg5oTBLbM0PJU4rz2nMxv/WjAvrgRLnheN0LlUUoZzICK6P8E04GBOIRXsoG3OBh+BG3mwLD1142GFYSBkWev3Z+eTpHmJx4oFuI+OnSjhT2LBAdSF9FRvIxInL57tSERSPp/2knNFKkQteAniIjNaXgKpjsIRj062pOOOYL/NTHsMn6wUle/3HRQtxrcY4oCbZqJCsNQxBCfIYGKxYgnNf4p9jveuwotQIHofFpAb0xwbXo7wGP5AiHUTdI8IiZOgMrwZ6EB1Pnd0cyqDm21JEuE0i1xcxiPLuzOwmL/BFKb8+XKUwC+ZA0D19BHT11kUv1nx9cmc1q7/YQPsNK7Z4YEf+Um9hlFOHtqmV9Um0H1AK7B3yXnXSM+wqRF3silh6ypFNbMicHUzv3ZBJ81DzlSA/+u0h/GuFEfxHQo4gACG+4ekNz5ZvaDCe+vy19BNf7he1yqSMRTcNkNKkA1BUCsks85AwJOX+QvfVDUsezkWwDN+CgLqZSMd1LfB/lIhpC+yMV1GvIn9lCc929UsOgxERKuFYbJ1ZslV8RrPQ8OFpwWyRY48+cZoBIZ0aeqidi4ra1+kArrLIHdKUyxydWc1tlEzcYu1js=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-local
    branch: master
