language: node_js
node_js:
- 6
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: "5HpF0RWm4DxatXRHjxrZZAih+nhFpxFr5ymbuMx9u6q9DCkt9vPJ2dqph+1VP+IqDDFCtQx59xNSpI3jzLRmKUcKYtGxHiaRHFeS4CM0aRFuoHKMqRx++XUNHCahibrxOF92k8CuW5tkVtkjXYImyxmLdcpkIxL0bmV2D9u8QA6qc+/VCIYHpxoO3eNMmMDU3UPnkwEBtQRgmhIXc9vdhlwffQjC8Fdz4XaVnroaCx2dvZeoRnNAvwfhb7Fnf7441yG1OuksOjbj5/AYGq3Z2SEvV58U53qvIvAyg23gtKwf3qWEymMm1dghU/atH42rAfStYx+pMc4wlkex9o1b42itryKd0FzCJR9KHF60URfHrLRpTUDI4BN0Ff9UU+l3CZB5mtKqC/My55DdTai0OX2Pu1+gj0J8z9Ih/ssfEwZNzPjuBaV32omsMS0DmXiDN9/nIYEtBpIocP+HgGtxRivg15ymMT2KXeGzKZv+5vF4BcsBqoR3K8GVbZqdmaSmQ1TeQzakO+kmlhV4DEhg6NLs7mHt343IZhoffGSvpC6F4991Urb9kqxAnXyQ8Xv1zsssOqCfIJQr84OEfrFHVhZpp7V+1sPipB8YZ7vJ+WRbwI/QTdt1ONberdTgFjpk/2FT6H4RmLTxycZ+uw62GTP1iKy9lRuWBa+bn7n4cAA="
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-local
    branch: master
