version: "3"

services:
  kuzzle:
    image: kuzzleio/plugin-dev:2
    command: |
      bash -c '
        npm i -g nodemon

        if [ ! -d plugins/enabled/kuzzle-plugin-auth-passport-local/node_modules ]; then
          npm ci --prefix plugins/enabled/kuzzle-plugin-auth-passport-local
        fi

        until curl -sf -o /dev/null $${kuzzle_services__storageEngine__client__node}; do
          printf "."
          sleep 1
        done
        echo

        nodemon -w plugins/enabled/kuzzle-plugin-auth-passport-local bin/start-kuzzle-server
      '
    volumes:
      - .:/var/app/plugins/enabled/kuzzle-plugin-auth-passport-local
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "9229:9229"
      - "7512:7512"
    environment:
      kuzzle_services__storageEngine__client__node: http://elasticsearch:9200
      kuzzle_services__internalCache__node__host: redis
      kuzzle_services__memoryStorage__node__host: redis
      NODE_ENV: development
      DEBUG: kuzzle-plugin-auth-passport-local
      DEBUG_COLORS: "true"

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:7.3.0
    ulimits:
      nofile: 65536
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
